version: "3"

services:
  reverse-proxy:
    container_name: reverse-proxy
    image: tinyproxy-env-conf
    build: https://github.com/y-du/tinyproxy-env-conf.git
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      - TP_User=tinyproxy
      - TP_Group=tinyproxy
      - TP_ViaProxyName="LOPCO-API"
      - TP_Port=8000
      - TP_LogLevel=Info
      - TP_ReverseOnly=Yes
      - TP_MaxClients=100
      - TP_MinSpareServers=10
      - TP_MaxSpareServers=10
      - TP_StartServers=10
      - TP_Timeout=600
      - TP_1_ReversePath="/job-manager/" "http://job-manager/"
      - TP_2_ReversePath="/machine-registry/" "http://machine-registry/"
      - TP_3_ReversePath="/pipeline-registry/" "http://pipeline-registry/"
      - TP_4_ReversePath="/worker-registry/" "http://worker-registry/"
      - TP_5_ReversePath="/protocol-adapter-registry/" "http://protocol-adapter-registry/"
      - TP_6_ReversePath="/deployment-manager/" "http://deployment-manager/"
    networks:
      - lopco-network
    labels:
      - "lopco-type=core"
    restart: unless-stopped

  job-manager:
    container_name: job-manager
    image: job-manager
    build: https://github.com/PlatonaM/lopco-job-manager.git
    expose:
      - 80
    volumes:
      - job_manager_data:/usr/src/app/data
      - data_cache:/data_cache
    environment:
      - CONF_LOGGER_LEVEL=debug
    networks:
      - lopco-network
    labels:
      - "lopco-type=core"
    restart: unless-stopped

  machine-registry:
    container_name: machine-registry
    image: crud-template-service
    build: https://github.com/y-du/crud-template-service.git
    expose:
      - 80
    volumes:
      - machine_registry_data:/usr/src/app/data
    environment:
      - CRUDCONF_LOGGER_NAME=machine-registry
      - CRUDCONF_LOGGER_LEVEL=debug
      - CRUDCONF_ENDPOINT_NAME=machines
      - CRUDCONF_ENDPOINT_FULL_COLLECTION=True
    networks:
      - lopco-network
    labels:
      - "lopco-type=core"
    restart: unless-stopped

  pipeline-registry:
    container_name: pipeline-registry
    image: crud-template-service
    build: https://github.com/y-du/crud-template-service.git
    expose:
      - 80
    volumes:
      - pipeline_registry_data:/usr/src/app/data
    environment:
      - CRUDCONF_LOGGER_NAME=pipeline-registry
      - CRUDCONF_LOGGER_LEVEL=debug
      - CRUDCONF_ENDPOINT_NAME=pipelines
      - CRUDCONF_ENDPOINT_ALLOW_POST=True
      - CRUDCONF_ENDPOINT_FULL_COLLECTION=True
    networks:
      - lopco-network
    labels:
      - "lopco-type=core"
    restart: unless-stopped

  worker-registry:
    container_name: worker-registry
    image: crud-template-service
    build: https://github.com/y-du/crud-template-service.git
    expose:
      - 80
    volumes:
      - worker_registry_data:/usr/src/app/data
    environment:
      - CRUDCONF_LOGGER_NAME=worker-registry
      - CRUDCONF_LOGGER_LEVEL=debug
      - CRUDCONF_ENDPOINT_NAME=workers
      - CRUDCONF_ENDPOINT_ALLOW_POST=True
      - CRUDCONF_ENDPOINT_FULL_COLLECTION=True
    networks:
      - lopco-network
    labels:
      - "lopco-type=core"
    restart: unless-stopped

  protocol-adapter-registry:
    container_name: protocol-adapter-registry
    image: crud-template-service
    build: https://github.com/y-du/crud-template-service.git
    expose:
      - 80
    volumes:
      - protocol_adapter_registry_data:/usr/src/app/data
    environment:
      - CRUDCONF_LOGGER_NAME=protocol-adapter-registry
      - CRUDCONF_LOGGER_LEVEL=debug
      - CRUDCONF_ENDPOINT_NAME=protocol-adapters
      - CRUDCONF_ENDPOINT_ALLOW_POST=True
      - CRUDCONF_ENDPOINT_FULL_COLLECTION=True
    networks:
      - lopco-network
    labels:
      - "lopco-type=core"
    restart: unless-stopped

  deployment-manager:
    container_name: deployment-manager
    image: deployment-manager
    build: https://github.com/PlatonaM/lopco-deployment-manager.git
    expose:
      - 80
    environment:
      - CONF_LOGGER_LEVEL=debug
      - CONF_DOCKER_SOCKET=unix://var/run/docker.sock
      - CONF_DOCKER_NETWORK_NAME=core_lopco-network
      - CONF_DOCKER_DISABLE_RM=False
      - CONF_DATACACHE_VOLUME_NAME=core_data_cache
    networks:
      - lopco-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "lopco-type=core"
    restart: unless-stopped

  gui:
    container_name: gui
    image: gui
    build: https://github.com/PlatonaM/lopco-gui.git
    expose:
      - 80
    ports:
      - 8080:80
    networks:
      - lopco-network
    labels:
      - "lopco-type=core"
    restart: unless-stopped

volumes:
  data_cache:
  job_manager_data:
  machine_registry_data:
  pipeline_registry_data:
  worker_registry_data:
  protocol_adapter_registry_data:

networks:
  lopco-network:
    ipam:
      config:
        - subnet: 10.20.0.0/16
